trigger:
  tags:
    include:
      - '*'

pr: none

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: api-bundle
      type: github
      endpoint: keboola
      name: keboola/api-bundle
    - repository: azure-api-client
      type: github
      endpoint: keboola
      name: keboola/azure-api-client
    - repository: configuration-variables-resolver
      type: github
      endpoint: keboola
      name: keboola/configuration-variables-resolver
    - repository: doctrine-retry-bundle
      type: github
      endpoint: keboola
      name: keboola/doctrine-retry-bundle
    - repository: input-mapping
      type: github
      endpoint: keboola
      name: keboola/input-mapping
    - repository: k8s-client
      type: github
      endpoint: keboola
      name: keboola/k8s-client
    - repository: logging-bundle
      type: github
      endpoint: keboola
      name: keboola/logging-bundle
    - repository: messenger-bundle
      type: github
      endpoint: keboola
      name: keboola/messenger-bundle
    - repository: output-mapping
      type: github
      endpoint: keboola
      name: keboola/output-mapping
    - repository: permission-checker
      type: github
      endpoint: keboola
      name: keboola/permission-checker
    - repository: php-key-generator
      type: github
      endpoint: keboola
      name: keboola/php-key-generator
    - repository: php-test-utils
      type: github
      endpoint: keboola
      name: keboola/php-test-utils
    - repository: query-service-api-php-client
      type: github
      endpoint: keboola
      name: keboola/query-service-api-php-client
    - repository: sandboxes-service-api-php-client
      type: github
      endpoint: keboola
      name: keboola/sandboxes-service-api-php-client
    - repository: php-storage-names-sanitizer
      type: github
      endpoint: keboola
      name: keboola/php-storage-names-sanitizer
    - repository: service-client
      type: github
      endpoint: keboola
      name: keboola/service-client
    - repository: settle
      type: github
      endpoint: keboola
      name: keboola/settle
    - repository: slicer
      type: github
      endpoint: keboola
      name: keboola/slicer
    - repository: staging-provider
      type: github
      endpoint: keboola
      name: keboola/staging-provider
    - repository: sync-actions-api-php-client
      type: github
      endpoint: keboola
      name: keboola/sync-actions-api-php-client
    - repository: vault-api-php-client
      type: github
      endpoint: keboola
      name: keboola/vault-api-php-client

variables:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  - template: azure-pipelines/jobs/split-library.yml
    parameters:
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/api-bundle/')
      sourceRepo: platform-libraries
      targetRepo: api-bundle
      libraryPath: libs/api-bundle
      tagPrefix: api-bundle/

  - template: azure-pipelines/jobs/split-library.yml
    parameters:
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/azure-api-client/')
      sourceRepo: platform-libraries
      targetRepo: azure-api-client
      libraryPath: libs/azure-api-client
      tagPrefix: azure-api-client/

  - template: azure-pipelines/jobs/split-library.yml
    parameters:
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/configuration-variables-resolver/')
      sourceRepo: platform-libraries
      targetRepo: configuration-variables-resolver
      libraryPath: libs/configuration-variables-resolver
      tagPrefix: configuration-variables-resolver/

  - template: azure-pipelines/jobs/split-library.yml
    parameters:
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/doctrine-retry-bundle/')
      sourceRepo: platform-libraries
      targetRepo: doctrine-retry-bundle
      libraryPath: libs/doctrine-retry-bundle
      tagPrefix: doctrine-retry-bundle/

  - template: azure-pipelines/jobs/split-library.yml
    parameters:
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/input-mapping/')
      sourceRepo: platform-libraries
      targetRepo: input-mapping
      libraryPath: libs/input-mapping
      tagPrefix: input-mapping/

  - template: azure-pipelines/jobs/split-library.yml
    parameters:
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/k8s-client/')
      sourceRepo: platform-libraries
      targetRepo: k8s-client
      libraryPath: libs/k8s-client
      tagPrefix: k8s-client/

  - template: azure-pipelines/jobs/split-library.yml
    parameters:
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/key-generator/')
      sourceRepo: platform-libraries
      targetRepo: php-key-generator
      libraryPath: libs/key-generator
      tagPrefix: key-generator/

  - template: azure-pipelines/jobs/split-library.yml
    parameters:
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/logging-bundle/')
      sourceRepo: platform-libraries
      targetRepo: logging-bundle
      libraryPath: libs/logging-bundle
      tagPrefix: logging-bundle/

  - template: azure-pipelines/jobs/split-library.yml
    parameters:
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/messenger-bundle/')
      sourceRepo: platform-libraries
      targetRepo: messenger-bundle
      libraryPath: libs/messenger-bundle
      tagPrefix: messenger-bundle/

  - template: azure-pipelines/jobs/split-library.yml
    parameters:
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/output-mapping/')
      sourceRepo: platform-libraries
      targetRepo: output-mapping
      libraryPath: libs/output-mapping
      tagPrefix: output-mapping/

  - template: azure-pipelines/jobs/split-library.yml
    parameters:
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/permission-checker/')
      sourceRepo: platform-libraries
      targetRepo: permission-checker
      libraryPath: libs/permission-checker
      tagPrefix: permission-checker/

  - template: azure-pipelines/jobs/split-library.yml
    parameters:
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/php-test-utils/')
      sourceRepo: platform-libraries
      targetRepo: php-test-utils
      libraryPath: libs/php-test-utils
      tagPrefix: php-test-utils/

  - template: azure-pipelines/jobs/split-library.yml
    parameters:
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/query-service-api-client/')
      sourceRepo: platform-libraries
      targetRepo: query-service-api-php-client
      libraryPath: libs/query-service-api-client
      tagPrefix: query-service-api-client/

  - template: azure-pipelines/jobs/split-library.yml
    parameters:
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/sandboxes-service-api-client/')
      sourceRepo: platform-libraries
      targetRepo: sandboxes-service-api-php-client
      libraryPath: libs/sandboxes-service-api-client
      tagPrefix: sandboxes-service-api-client/

  - template: azure-pipelines/jobs/split-library.yml
    parameters:
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/php-storage-names-sanitizer/')
      sourceRepo: platform-libraries
      targetRepo: php-storage-names-sanitizer
      libraryPath: libs/php-storage-names-sanitizer
      tagPrefix: php-storage-names-sanitizer/

  - template: azure-pipelines/jobs/split-library.yml
    parameters:
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/service-client/')
      sourceRepo: platform-libraries
      targetRepo: service-client
      libraryPath: libs/service-client
      tagPrefix: service-client/

  - template: azure-pipelines/jobs/split-library.yml
    parameters:
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/settle/')
      sourceRepo: platform-libraries
      targetRepo: settle
      libraryPath: libs/settle
      tagPrefix: settle/

  - template: azure-pipelines/jobs/split-library.yml
    parameters:
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/slicer/')
      sourceRepo: platform-libraries
      targetRepo: slicer
      libraryPath: libs/slicer
      tagPrefix: slicer/

  - template: azure-pipelines/jobs/split-library.yml
    parameters:
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/staging-provider/')
      sourceRepo: platform-libraries
      targetRepo: staging-provider
      libraryPath: libs/staging-provider
      tagPrefix: staging-provider/

  - template: azure-pipelines/jobs/split-library.yml
    parameters:
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/sync-actions-api-php-client/')
      sourceRepo: platform-libraries
      targetRepo: sync-actions-api-php-client
      libraryPath: libs/sync-actions-api-php-client
      tagPrefix: sync-actions-api-php-client/

  - template: azure-pipelines/jobs/split-library.yml
    parameters:
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/vault-api-client/')
      sourceRepo: platform-libraries
      targetRepo: vault-api-php-client
      libraryPath: libs/vault-api-client
      tagPrefix: vault-api-client/
