trigger:
  tags:
    include:
      - '*'

pr: none

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: input-mapping
      type: github
      endpoint: keboola
      name: keboola/input-mapping

variables:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  - template: azure-pipelines/jobs/split-library.yml
    parameters:
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/input-mapping/')
      sourceRepo: platform-libraries
      targetRepo: input-mapping
      libraryPath: libs/input-mapping
      tagPrefix: input-mapping/

