trigger:
  tags:
    include:
      - '*'

pr: none

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: api-bundle
      type: github
      endpoint: keboola
      name: keboola/api-bundle
    - repository: azure-api-client
      type: github
      endpoint: keboola
      name: keboola/azure-api-client
    - repository: configuration-variables-resolver
      type: github
      endpoint: keboola
      name: keboola/configuration-variables-resolver
    - repository: input-mapping
      type: github
      endpoint: keboola
      name: keboola/input-mapping
    - repository: k8s-client
      type: github
      endpoint: keboola
      name: keboola/k8s-client
    - repository: logging-bundle
      type: github
      endpoint: keboola
      name: keboola/logging-bundle
    - repository: output-mapping
      type: github
      endpoint: keboola
      name: keboola/output-mapping
    - repository: permission-checker
      type: github
      endpoint: keboola
      name: keboola/permission-checker
    - repository: settle
      type: github
      endpoint: keboola
      name: keboola/settle
    - repository: staging-provider
      type: github
      endpoint: keboola
      name: keboola/staging-provider
    - repository: vault-api-client
      type: github
      endpoint: keboola
      name: keboola/vault-api-php-client

variables:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  - template: azure-pipelines/jobs/split-library.yml
    parameters:
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/api-bundle/')
      sourceRepo: platform-libraries
      targetRepo: api-bundle
      libraryPath: libs/api-bundle
      tagPrefix: api-bundle/

  - template: azure-pipelines/jobs/split-library.yml
    parameters:
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/azure-api-client/')
      sourceRepo: platform-libraries
      targetRepo: azure-api-client
      libraryPath: libs/azure-api-client
      tagPrefix: azure-api-client/

  - template: azure-pipelines/jobs/split-library.yml
    parameters:
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/configuration-variables-resolver/')
      sourceRepo: platform-libraries
      targetRepo: configuration-variables-resolver
      libraryPath: libs/configuration-variables-resolver
      tagPrefix: configuration-variables-resolver/

  - template: azure-pipelines/jobs/split-library.yml
    parameters:
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/input-mapping/')
      sourceRepo: platform-libraries
      targetRepo: input-mapping
      libraryPath: libs/input-mapping
      tagPrefix: input-mapping/

  - template: azure-pipelines/jobs/split-library.yml
    parameters:
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/k8s-client/')
      sourceRepo: platform-libraries
      targetRepo: k8s-client
      libraryPath: libs/k8s-client
      tagPrefix: k8s-client/

  - template: azure-pipelines/jobs/split-library.yml
    parameters:
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/logging-bundle/')
      sourceRepo: platform-libraries
      targetRepo: logging-bundle
      libraryPath: libs/logging-bundle
      tagPrefix: logging-bundle/

  - template: azure-pipelines/jobs/split-library.yml
    parameters:
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/output-mapping/')
      sourceRepo: platform-libraries
      targetRepo: output-mapping
      libraryPath: libs/output-mapping
      tagPrefix: output-mapping/

  - template: azure-pipelines/jobs/split-library.yml
    parameters:
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/permission-checker/')
      sourceRepo: platform-libraries
      targetRepo: permission-checker
      libraryPath: libs/permission-checker
      tagPrefix: permission-checker/

  - template: azure-pipelines/jobs/split-library.yml
    parameters:
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/settle/')
      sourceRepo: platform-libraries
      targetRepo: settle
      libraryPath: libs/settle
      tagPrefix: settle/

  - template: azure-pipelines/jobs/split-library.yml
    parameters:
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/staging-provider/')
      sourceRepo: platform-libraries
      targetRepo: staging-provider
      libraryPath: libs/staging-provider
      tagPrefix: staging-provider/


  - template: azure-pipelines/jobs/split-library.yml
    parameters:
      condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/vault-api-client/')
      sourceRepo: platform-libraries
      targetRepo: vault-api-client
      libraryPath: libs/vault-api-client
      tagPrefix: vault-api-client/
