version: "3.4"

services:
  mockserver:
    image: mockserver/mockserver:5.13.2

  dev: &dev
    build: &dev-build
      context: .
    working_dir: /code
    command: [/bin/bash]
    volumes:
      - .:/code

  dev74:
    <<: *dev
    image: keboola/php-dev74
    build:
      <<: *dev-build
      args:
        PHP_VERSION: "7.4"

  dev81: &dev81
    <<: *dev
    image: keboola/php-dev81
    build:
      <<: *dev-build
      args:
        PHP_VERSION: "8.1"

  dev82: &dev82
    <<: *dev
    image: keboola/php-dev82
    build:
      <<: *dev-build
      args:
        PHP_VERSION: "8.2"
        XDEBUG_VERSION: ""
    extra_hosts:
      - "host.docker.internal:host-gateway"

  dev-api-bundle:
    <<: *dev81
    image: keboola/api-bundle
    working_dir: /code/libs/api-bundle

  dev-azure-api-client:
    <<: *dev81
    image: keboola/azure-api-client
    working_dir: /code/libs/azure-api-client
    depends_on:
      - mockserver

  dev-configuration-variables-resolver:
    <<: *dev82
    image: keboola/configuration-variables-resolver
    working_dir: /code/libs/configuration-variables-resolver
    environment:
      - STORAGE_API_TOKEN
      - STORAGE_API_TOKEN_MASTER
      - STORAGE_API_URL

  dev-input-mapping:
    <<: *dev
    image: keboola/input-mapping
    working_dir: /code/libs/input-mapping
    environment:
      - STORAGE_API_TOKEN
      - STORAGE_API_TOKEN_MASTER
      - STORAGE_API_URL
      - RUN_SYNAPSE_TESTS
      - SYNAPSE_STORAGE_API_TOKEN
      - SYNAPSE_STORAGE_API_URL

  dev-k8s-client:
    <<: *dev81
    image: keboola/k8s-client
    working_dir: /code/libs/k8s-client

  dev-messenger-bundle:
    <<: *dev82
    working_dir: /code/libs/messenger-bundle
    environment:
      APP_ENV: dev

  dev-output-mapping:
    <<: *dev
    image: keboola/output-mapping
    working_dir: /code/libs/output-mapping
    environment:
      - STORAGE_API_TOKEN
      - STORAGE_API_TOKEN_MASTER
      - STORAGE_API_URL
      - RUN_SYNAPSE_TESTS
      - SYNAPSE_STORAGE_API_TOKEN
      - SYNAPSE_STORAGE_API_URL

  dev-permission-checker:
    <<: *dev81
    image: keboola/permission-checker
    working_dir: /code/libs/permission-checker

  dev-sandboxes-service-api-client:
    <<: *dev82
    image: keboola/sandboxes-service-api-client
    working_dir: /code/libs/sandboxes-service-api-client
    depends_on:
      - mockserver

  dev-service-client:
    <<: *dev81
    image: keboola/service-client
    working_dir: /code/libs/service-client

  dev-settle:
    <<: *dev
    image: keboola/settle
    working_dir: /code/libs/settle

  dev-staging-provider:
    <<: *dev
    image: keboola/staging-provider
    working_dir: /code/libs/staging-provider
    environment:
      - STORAGE_API_TOKEN
      - STORAGE_API_URL
      - RUN_SYNAPSE_TESTS
      - SYNAPSE_STORAGE_API_TOKEN
      - SYNAPSE_STORAGE_API_URL

  dev-vault-api-client:
    <<: *dev82
    image: keboola/vault-api-client
    working_dir: /code/libs/vault-api-client

  dev-slicer:
    <<: *dev
    image: keboola/slicer
    working_dir: /code/libs/slicer

  dev-logging-bundle:
    <<: *dev
    working_dir: /code/libs/logging-bundle
