version: "3.4"

services:
  dev-input-mapping:
    profiles: [dev]
    build:
      context: .
      target: dev
    working_dir: /code/libs/input-mapping
    volumes:
      - .:/code
    environment:
      - STORAGE_API_TOKEN
      - STORAGE_API_TOKEN_MASTER
      - STORAGE_API_URL
      - RUN_SYNAPSE_TESTS
      - SYNAPSE_STORAGE_API_TOKEN
      - SYNAPSE_STORAGE_API_URL

  ci-input-mapping:
    profiles: [ci]
    image: keboola/input-mapping
    build:
      context: .
      target: input-mapping
    environment:
      - STORAGE_API_TOKEN
      - STORAGE_API_TOKEN_MASTER
      - STORAGE_API_URL
      - RUN_SYNAPSE_TESTS
      - SYNAPSE_STORAGE_API_TOKEN
      - SYNAPSE_STORAGE_API_URL

  dev-staging-provider:
    profiles: [dev]
    build:
      context: .
      target: dev
    working_dir: /code/libs/staging-provider
    volumes:
      - .:/code
    environment:
      - STORAGE_API_TOKEN
      - STORAGE_API_URL
      - RUN_SYNAPSE_TESTS
      - SYNAPSE_STORAGE_API_TOKEN
      - SYNAPSE_STORAGE_API_URL

  dev-output-mapping:
    profiles: [dev]
    build:
      context: .
      target: dev
    working_dir: /code/libs/output-mapping
    volumes:
      - .:/code
    environment:
      - STORAGE_API_TOKEN
      - STORAGE_API_TOKEN_MASTER
      - STORAGE_API_URL
      - RUN_SYNAPSE_TESTS
      - SYNAPSE_STORAGE_API_TOKEN
      - SYNAPSE_STORAGE_API_URL

  ci-staging-provider:
    profiles: [ci]
    image: keboola/staging-provider
    build:
      context: .
      target: staging-provider
    environment:
      - STORAGE_API_TOKEN
      - STORAGE_API_URL
      - RUN_SYNAPSE_TESTS
      - SYNAPSE_STORAGE_API_TOKEN
      - SYNAPSE_STORAGE_API_URL

  ci-output-mapping:
    profiles: [ci]
    image: keboola/output-mapping
    build:
      context: .
      target: output-mapping
    environment:
      - STORAGE_API_TOKEN
      - STORAGE_API_TOKEN_MASTER
      - STORAGE_API_URL
      - RUN_SYNAPSE_TESTS
      - SYNAPSE_STORAGE_API_TOKEN
      - SYNAPSE_STORAGE_API_URL
