version: "3.4"

services:
  mockserver:
    image: mockserver/mockserver:5.13.2

  dev: &dev
    profiles: [ ci, dev ]
    build: &dev-build
      context: .
      target: dev
    working_dir: /code
    command: [/bin/bash]
    volumes:
      - .:/code

  dev-azure-api-client:
    profiles: [dev]
    build:
      <<: *dev-build
      args:
        PHP_VERSION: "8.1"
    working_dir: /code/libs/azure-api-client
    volumes:
      - .:/code
    depends_on:
      - mockserver

  dev-input-mapping:
    profiles: [dev]
    build:
      context: .
      target: dev
    working_dir: /code/libs/input-mapping
    volumes:
      - .:/code
    environment:
      - STORAGE_API_TOKEN
      - STORAGE_API_TOKEN_MASTER
      - STORAGE_API_URL
      - RUN_SYNAPSE_TESTS
      - SYNAPSE_STORAGE_API_TOKEN
      - SYNAPSE_STORAGE_API_URL

  ci-input-mapping:
    profiles: [ci]
    image: keboola/input-mapping
    build:
      context: .
      target: input-mapping
    environment:
      - STORAGE_API_TOKEN
      - STORAGE_API_TOKEN_MASTER
      - STORAGE_API_URL
      - RUN_SYNAPSE_TESTS
      - SYNAPSE_STORAGE_API_TOKEN
      - SYNAPSE_STORAGE_API_URL

  dev-k8s-client:
    profiles: [dev]
    build:
      <<: *dev-build
      args:
        PHP_VERSION: "8.1"
    working_dir: /code/libs/k8s-client
    volumes:
      - .:/code

  dev-staging-provider:
    profiles: [dev]
    build:
      context: .
      target: dev
    working_dir: /code/libs/staging-provider
    volumes:
      - .:/code
    environment:
      - STORAGE_API_TOKEN
      - STORAGE_API_URL
      - RUN_SYNAPSE_TESTS
      - SYNAPSE_STORAGE_API_TOKEN
      - SYNAPSE_STORAGE_API_URL

  dev-output-mapping:
    profiles: [dev]
    build:
      context: .
      target: dev
    working_dir: /code/libs/output-mapping
    volumes:
      - .:/code
    environment:
      - STORAGE_API_TOKEN
      - STORAGE_API_TOKEN_MASTER
      - STORAGE_API_URL
      - RUN_SYNAPSE_TESTS
      - SYNAPSE_STORAGE_API_TOKEN
      - SYNAPSE_STORAGE_API_URL

  ci-staging-provider:
    profiles: [ci]
    image: keboola/staging-provider
    build:
      context: .
      target: staging-provider
    environment:
      - STORAGE_API_TOKEN
      - STORAGE_API_URL
      - RUN_SYNAPSE_TESTS
      - SYNAPSE_STORAGE_API_TOKEN
      - SYNAPSE_STORAGE_API_URL

  ci-output-mapping:
    profiles: [ci]
    image: keboola/output-mapping
    build:
      context: .
      target: output-mapping
    environment:
      - STORAGE_API_TOKEN
      - STORAGE_API_TOKEN_MASTER
      - STORAGE_API_URL
      - RUN_SYNAPSE_TESTS
      - SYNAPSE_STORAGE_API_TOKEN
      - SYNAPSE_STORAGE_API_URL

  dev-configuration-variables-resolver:
    profiles: [ dev ]
    build:
      context: .
      target: dev
    working_dir: /code/libs/configuration-variables-resolver
    environment:
      - STORAGE_API_TOKEN
      - STORAGE_API_TOKEN_MASTER
      - STORAGE_API_URL

  ci-configuration-variables-resolver:
    profiles: [ ci ]
    image: keboola/configuration-variables-resolver
    build:
      context: .
      target: configuration-variables-resolver
    environment:
      - STORAGE_API_TOKEN
      - STORAGE_API_TOKEN_MASTER
      - STORAGE_API_URL

  dev-settle:
    profiles: [ dev ]
    build:
      context: .
      target: dev
    working_dir: /code/libs/settle

  ci-settle:
    profiles: [ ci ]
    image: keboola/settle
    build:
      context: .
      target: settle
