<?php


namespace Keboola\OutputMapping\Tests\Writer;


class TableDefinitionTest extends BaseWriterTest
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}
