name: lib-sync-actions-api-php-client
on:
  workflow_call: {}

concurrency:
  group: sync-actions-api-php-client-lock
  cancel-in-progress: false

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build image
        run: docker compose build dev-sync-actions-api-php-client
      - name: Run tests
        env:
          HOSTNAME_SUFFIX: ${{ vars.HOSTNAME_SUFFIX_GCP }}
          STORAGE_API_TOKEN: ${{ secrets.SYNC_ACTIONS_CLIENT__STORAGE_API_TOKEN_GCP }}
        run: docker compose run --rm dev-sync-actions-api-php-client bash -c 'composer install && composer ci'
      - name: Show logs on failure
        if: failure()
        run: docker compose logs
